#+TITLE:Curriculum Vitae
* Personalia
- Naam:              	CV_1
- Adres:                    	
- Postcode/Woonplaats	
- Telefoonnummer:       
- E-mail:                        
- Geboortedatum:          1953
- Nationaliteit:               Nederlandse
- Burgerlijke staat         Gehuwd

* Werkervaring   

** 2011-heden
Gastvrouw verzorgingstehuis XXXX te DXXXX	

Taken: 
- voorbereiden ontbijt en lunch
- bedienen ontbijt en lunch
			            
** 2010-2011
Gastvrouw partyXXXX  XXXX te DXXXX

Taken:
- gasten ontvangen en bedienen

** 2009-2010
Kantinemedewerkster, XXXX WXXXX te DXXXX

Taken:
- voorbereiden lunch
- bedienen bij de lunch
- koffie en thee verzorgen tijdens vergaderingen in kantoren

** 2001-2009
Gastvrouw, begeleidster en kok restaurant/eetcafé HXXXX te Deventer. Hier werken leerlingen met een verstandelijke beperking

Taken:
- gasten ontvangen en bedienen
- leerlingen begeleiden in hun werk in de keuken en het   
  restaurant
- mentortaken voor een aantal leerlingen
- koken voor de lunch en diner

** 1998-1999
Gastvrouw en serveerster restaurant XXXX te TXXXX

Taken:
- gasten ontvangen en bedienen.
				
** 1996-1998
Kok en serveerster restaurant/bistro de SXXXX te TXXXX
Taken:
- gasten ontvangen en bedienen
				- aantal dagen per week koken voor de lunch en het diner

** 1995-1996
Kok en serveerster restaurant de BXXXX te HXXXX

** 1994-1995
Gastvrouw en receptioniste congrescentrum/restaurant XXXX te CXXXX

** 1993-1994
Gastvrouw en receptioniste hotel/restaurant LXXXX te EXXXX

** 1991-1993
Gastvrouw en serveerster LXXXX te BXXXX

** 1990-1991
Verkoopster damesmodezaak te DXXXX

** 1987-1990
Activiteitenbegeleidster dagactiviteitencentrum de LXXXX te XXXX. Dit is een dagopvang voor mensen met een verstandelijke beperking

** 1980-1987
PR-medewerker bij PXXXX te EXXXX en verkoopster bij MXXXX te AXXXX

* Opleidingen                 

- 1997-1998: Opleiding gastvrouw horeca, SVH-diploma behaald
- 1986.1987: MBO verkoopkunde te AXXXX, diploma behaald
- 1965-1969: Mulo te HXXXX, diploma behaald

* Overige informatie

- In bezit van rijbewijs BE
- Talenkennis (spreken en verstaan): Engels (goed), Duits (goed) en Spaans (redelijk)
- Hobby’s: koken, tuinieren, puzzelen en creatief bezig zijn

 
* Profiel
- Naam: 			CV_1		
- Adres:				
- Postcode / plaats:	DXXXX
- Telefoon:			
- E-mail:		
- Geboortedatum: 	1953

** Wie ben ik
Mijn naam is CV_1, 59 jaar en getouwd met XXXX. Als persoon ben ik betrouwbaar, representatief, eerlijk, gastvrij en kan goed omgaan met stressvolle situaties. Verder ben ik flexibel en spreek ik diverse vreemde talen. Mijn sterkste punt is mijn veelzijdigheid. 

In mijn vrije tijd vind ik het leuk om te koken, te tuinieren (vooral kruiden), creatief bezig te zijn (zowel met bloemen als met hout en papier) en het knus maken van ons huis.

** Wat kan ik 
Ik heb de laatste 30 jaar in verschillende horecabedrijven gewerkt. Hier heb ik alle werkzaamheden uitgevoerd die er zijn, van afwassen tot het bedienen van gasten en het inwerken en begeleiden van nieuwe collega’s. Daarnaast heb ik de opleiding tot gastvrouw horeca met succes afgerond en het SVH-diploma behaald. Het werken in de horeca spreekt mij erg aan. Ik hou ervan om mensen te verzorgen en hen een mooie tijd te bezorgen. Het contact met de gasten is één  van de zaken die mij in het werk veel voldoening geven. 

Door de jaren heen heb ik altijd als er tijd was in de keuken gestaan waar ik heel veel heb geleerd op het gebied van koken en kon er mijn creativiteit in kwijt. Ook heb ik veel nieuwe collega’s ingewerkt en begeleid. Een onderdeel van het werk wat ik altijd met veel plezier heb gedaan. Op grond van mijn ervaringen en interesses denk ik dat ik een goede kandidaat ben voor een restaurant of hotel.

** Wat wil ik 
Graag zou ik mijn gastvrije houding en mijn jarenlange ervaring willen gebruiken om weer in een restaurant of hotel aan het werk te gaan. De functies die mij aanspreken zijn: gastvrouw, begeleider van mensen met een verstandelijke beperking in een horeca bedrijf, kok.

Ik vind het belangrijk om op een informele en leuke manier samen te werken met mijn collega’s. Eerlijkheid en respect zijn daarbij voor mij kernwoorden. Ik ben op zoek naar een leuke baan voor minimaal 20 uur of meer. 
* Sonar internal registration
** Werkzoekende registratie
- Naam:   CV_1
- Samenvatting: CV     
- Opleidingsniveau:   Basisonderwijs 
- Laatste beroep:   -- 
- Bemiddelingsberoepen:   [medewerker bedrijfscatering, gastvrouw horeca] 
- Eigenaar:   XXXX 
- Vestiging:   WERKbedrijf DXXXX 
- Bron:   Sonar 
- Datum Melding:   06-12-2011 
- Status:   Uitgeschreven 
- Doelgroep(en):   Geholpen door team werk.nl
 
** Regeling(en)    
- Presentatie op werk.nl:   Open 
- Inschrijfdatum:   04-02-2014  
- Uitschrijfdatum, -reden:   05-03-2014 , Verlopen inschrijving 
- Beschikbaar voor werk:   05-11-2010 
- Werken in de EU/EER:    
- CV+:   Nee 
- Matchen op vacatures:   Nee 
- Indicering:   WW Dienstverlening
 
** Participatietrede    
- (Vermoedelijk) eerste uitkeringsdag:   02-09-2010 
- Maximale uitkeringsdag:   06-01-2014 
** Persoonsgegevens
- Voornamen:   CV_1
- Achternaam:   CV_1 
- Roepnaam:   -- 
- Achternaam Partner:   XXXX 
- Geslacht en geboortedatum:   Vrouw, 1953 
- Burgerservicenummer:  XXXX 
- Nationaliteit:   Nederlandse 

** Adres- en Contactgegevens
- Woonadres:   XXXX
  DXXXX  
- Telefoon:   XXXX 
- E-mail:   XXXX
- E-mail bemiddeling:  XXXX

** Opleidingen
| Naam        | Diploma |      Vanaf |        Tot |
|-------------+---------+------------+------------|
| basisschool | Ja      | 05-11-2010 | 05-11-2010 |

- Opleidingsniveau   Basisonderwijs 
** Taalvaardigheid
   | Taal       | Niveau mondeling | Niveau schriftelijk |
   |------------+------------------+---------------------|
   | Nederlands | Goed             | Goed                |

** Arbeidsverleden
- Functie Werkgever: Vanaf Tot 
- Geen arbeidsverleden: geregistreerd. 
- Uren nog werkzaam:   0 uur/week 

** Bemiddeling
- Kansberoep: Geen kansberoep geregistreerd. 
- Bemiddelingsberoep: medewerker bedrijfscatering,gastvrouw horeca
- Competenties: Geen competenties geregistreerd. 
- Affiniteiten: Geen affiniteit geregistreerd. 
- Beroepssectoren: Geen beroepssector geregistreerd. 
- Competentie componenten (Wajong): Geen competentie component geregistreerd. 
- Beschikbaar:   Vanaf 05-11-2010, 32 uur per week  
- Dienstverband:   Vast 
- Onregelmatig werk:    Nee 

** Taaksoort
- Belastbaarheid: 
- Mobiliteit: 
- Werkomgeving:
- Eisen aan het werk: 
- Reizen naar het werk
  - Wijze van vervoer   Auto 
  - Reistijd / -afstand   Max. 60 km of 60 minuten 
  - Rijbewijs   BE 
