#+TITLE: Curriculum Vitae 
* Personal Information
- Name: CV_1 
- Address: 
- Postcode / Town 
- Phone: 
- E-mail: 
- Date of birth: 1953 
- Nationality: Dutch 
- Marital status Married 

* Work experience 

** 2011-present 
Hostess in a home XXXX to Dxxxx 

tasks: 
- Prepare breakfast and lunch 
- Serving breakfast and lunch 

** 2010-2011 
Hostess partyXXXX XXXX to Dxxxx 

tasks: 

- Receive and serve guests 

** 2009-2010
Canteen Assistant, XXXX Wxxxx to Dxxxx 

tasks: 

- Preparing lunch 
- Serving lunch 
- Organize coffee and tea during meetings in offices 

** 2001-2009
Hostess, counselor and cook in the restaurant / cafe HXXXX in Deventer. Students with intellectual disabilities work here.

tasks: 
- Receive and serve guests
- Guide students in their work in the kitchen and the restaurant 
- Mentor tasks for some students 
- Cooking for lunch and dinner 

** 1998-1999
Hostess and waitress restaurant XXXX to TXXXX 

tasks: 
- Receive and serve guests.

** 1996-1998
Cook and waitress restaurant / bistro SXXXX to TXXXX 

tasks: 
- Receive and serve guests
- Cooking for lunch and dinner a number of days per week

** 1995-1996
Cook and waitress in restaurant bxxxx to HXXXX 

** 1994-1995
Hostess and receptionist congress centre / restaurant XXXX to CXXXX 

** 1993-1994
Hostess and receptionist hotel / restaurant Lxxxx to Exxxx 

** 1991-1993
Hostess and waitress Lxxxx to bxxxx 

** 1990-1991
Saleswoman clothing store to Dxxxx 

** 1987-1990
Activities accompanist day activity center for the Lxxxx XXXX. This is a day care for people with intellectual disabilities 

** 1980-1987
PR assistant at Pxxxx to Exxxx and saleswoman at MXXXX to AXXXX 

* Education 

- 1997-1998: Training hostess hospitality, earned SVH-diploma 
- 1986.1987: MBO salesmanship to AXXXX, earned diploma 
- 1965-1969: Mulo to HXXXX, earned diploma

* Other Information 

- Driving license BE 
- Language skills (speaking and listening): English (good), German (good) and Spanish (reasonable) 
- Hobbies: cooking, gardening, puzzles and being creative 

* Profile 
- Name: CV_1 
- Address: 
- Postcode / Town: Dxxxx 
- Telephone: 
- E-mail: 
- Date of birth: 1953 

** Who am I?
My name is CV_1, 59 years and married to XXXX. As a person, I am reliable, representative, honest, hospitable and able to deal with stressful situations. Furthermore, I am flexible and I speak several foreign languages. My greatest strength is my versatility. 

In my free time I like to cook, gardening (especially herbs), to be creative (both with flowers as wood and paper) and making our home a cozy place. 

** What can I do
I have worked in various hospitality companies in the last 30 years. Here I've done all the work available, from washing dishes to serving guests and the training and supervising new colleagues. I also have successfully completed the training for hospitality hostess and obtained the SVH diploma. Working in the hospitality industry really appeals to me. I love to take care of people and ensuring they have a good time. The contact with guests is one of the things that give me great satisfaction in the work. 

Over the years I have always stood in the kitchen if there was time, where I learned quite a lot about cooking where I could release my creativity. I also introduced many new colleagues to the job and supervised them. This is one part of my work that I've always done with pleasure. Based on my experiences and interests, I think I'm a good candidate for a restaurant or hotel. 

** What I want
I would like to use my welcoming attitude and my years of experience again in a restaurant or hotel. The features that appeal to me are: host, supervisor of people with intellectual disabilities in a catering company, cook. 

I think it's important to work with my colleagues in an informal and fun way. Honesty and respect are keywords for me. I am looking for a job for a minimum of 20 hours or more.

* Sonar internal registration 
** Jobseeker Registration
- Name: CV_1 
- Summary: CV 
- Education: Primary 
- Last job: - 
- Mediation Occupations: [employee catering, hospitality hostess] 
- Owner: XXXX 
- Establishment: Werkbedrijf Dxxxx 
- Source: Sonar 
- Date of Notification: 06-12-2011 
- Status: unregistered 
- Target audience (s): Helped by team werk.nl 

** Arrangements (s) 
- Presentation at werk.nl: Open 
- Registration Date: 04-02-2014 
- Uitschrijfdatum, -reden: 05-03-2014, Expired Registration 
- Available to work: 05-11-2010 
- Working in the EU / EEA: 
- CV +: No 
- Matching to vacancies: No 
- Indexing: WW Services 

** Participation layer 
- (Probably) first day of dole: 02-09-2010 
- Maximum day of dole: 06-01-2014 
** Personal 
- First names: CV_1 
- Surname: CV_1 
- Nickname: - 
- Partner Name: XXXX 
- Sex and date of birth, Woman, 1953 
- Citizen Service Number: XXXX 
- Nationality: Dutch 

** Address and Contact Details 
- Residential address: XXXX 
Dxxxx 
- Phone: XXXX 
- E-mail: XXXX 
- E-mail mediation: XXXX 

** Training 

| Name   | Diploma |       From |         To |
|--------+---------+------------+------------|
| Basic School | Yes     | 05-11-2010 | 05-11-2010 |

- Education level: Primary Education 
** Proficiency 
 | Language | Level oral | Level writing |
 |----------+------------+---------------|
 | Dutch    | Good       | Good          |

** Employment history 
- Employer Job: From To 
- No employment: registered. 
- Hours worked are: 0 hours / week 

** Mediation 
- Probability Occupation: No chance appeal registered. 
- Mediation Occupation: employee catering, hospitality hostess 
- Competencies: No competencies registered. 
- Affinities: No affinity registered. 
- Business Sectors: No professional sector recorded. 
- Competence components (Wajong): No competency component registered. 
- Available: As of 05-11-2010, 32 hours per week 
- Employment: Permanent 
- Irregular employment: No 

** Job Type 
- Load: 
- Mobility: 
- Working environment: 
- Requirements to work: 
- Travel to work 
- Mode of transport Car 
- Travel time / distance for Max. 60 km or 60 minutes 
