#+TITLE:VISSER - JACQUELINE ANN 

* Beschrijving
Een betrouwbare en zelfverzekerde persoon met een onbetwistbare arbeidsethos. Na langer dan 16 jaar op zee en in de visserij gewerkt te hebben heb ik de reputatie gekeregen een zeer waardevol bemanningslid te zijn.

Na offshore gewerkt te hebben in moeilijke omstandigheden heeft hij bewezen dat hij kan voldoen aan zware prestatie doelstellingen in elke omgeving die hij heeft ondervonden binnen een strak tijdschema. 

Een veelzijdige en robuuste werker - uitmuntend in vele rollen gedurende vroegere dienstbetrekkingen, zoals het zelfstandig werken, binnen een team, als een mentor voor nieuwe medewerkers en als dek baas. 

* WERKERVARING 
** VISSER 
MV JACQUELINE ANN - Fraserburgh - augustus 2013 tot heden 

visser, mv gesskie senior, Lofoten eilanden, Noorwegen 

** visser 
- Mei 2013 tot juli 2013 
mv ocean way, Banff, Schotland 
** VISSER 
MV BRACODEN - januari 2012 tot april 2013 

Banff, schotland 
** VISSER 
- Januari 2011 tot januari 2012 

Defiance, Fraserburgh, Schotland 
April 2004 - januari 2011 

- Algemene dek baas 
- Netten herstellen 
- Basis motor reparaties 
- Draden splitsen
- Het laden en lossen van de vangst en materialen 
- Schilderen 
- Koken / poetsten
- De wacht houden (plotten van de koers en het besturen van de boot) 
- Beheer van voorraad en beheer van apparatuur. 
- mentor voor nieuwe bemanningsleden
- Hoofd van veiligheidsoefeningen naleving van regelgevende instanties / standaarden
- Onderzoek en ontwikkeling van een nieuwe visserij 
- Koken voor 5-10 bemanningsleden 
* EXTRA INFORMATIE 
Belangrijkste sterke:
- Brede kennis van- en ervaring met offshore werken. 
- Ervaring met het opleiden van nieuwe medewerkers. 
- Ervaring in offshore werken voor langere tijd met behoud van hoge standaards, moraal en enthousiasme. 
- Goede communicatieve vaardigheden. 
* PROFFESSIONELE ontwikkeling 
- Geldig Offshore BOSIET 
- Geldig Offshore Medisch certificaat UK & Noors
- Minimale Industriele veiligheids training
- Kennis van veiligheid
- Basis EHBO 
- Basis voor brandbestrijding 
- Food Hygiene Certificaat 
- Noorse ontsnappingschute
