#+TITLE:John Doe
* FISHERMAN - MV JACQUELINE ANN
Banff - Email me on Indeed: 

A reliable and confident individual with an unquestionable work ethos. Having worked at sea in the fishing industry for over 16 years has gained the reputation as a very valuable crew member. 

Having worked offshore in arduous conditions has proven he can meet tough performance objectives in all environments he has encountered within tight timescale.

A versatile and robust worker - performing in many roles throughout previous employment such as working alone, within a team, as a mentor for new employees and as deck boss.

* WORK EXPERIENCE
** FISHERMAN
MV JACQUELINE ANN - Fraserburgh - August 2013 to Present

fisherman, mv gesskie senior, lofoten islands, norway
** fisherman
- May 2013 to July 2013
mv ocean way, banff, scotland
** FISHERMAN
MV BRACODEN - January 2012 to April 2013
banff, scotland
** FISHERMAN
- January 2011 to January 2012
defiance, fraserburgh, scotland
April 2004 - January 2011n

- Overall deck boss
- Net mending
- Basic engine repairs
- Wire splicing
- Loading and offloading of catch and materials
- Painting
- Cooking/cleaning
- Watch keeping (plotting course and navigating the boat)
- Vital stores and equipment management.
- New crew member mentor
- Head of safety drills ensuring compliance with regulatory authorities/standards
- Research and development of a new fishery
- Cook for 5-10 crew members
* ADDITIONAL INFORMATION
** KEY STRENGTHS
- Wide Knowledge and experience of working offshore.
- Experience of training new employees.
- Experience in working offshore for long periods whilst maintaining high standards, morale and enthusiasm.
- Good communication skills.
** PROFFESSIONAL development
- Valid Offshore BOSIET
- Valid Offshore Medical UK & Norwegian
- MIST Training
- Safety Awareness
- Basic First Aid
- Basic Fire Fighting
- Food Hygiene Certificate
- Norwegian escape chute
