#+TITLE:Experienced tour guide Single trips 

For the ANONYMOUS, is ANONYMOUS is looking for enthusiastic tour guides with experience. Are you the proactive, compliant and active tour guide we are looking for? Visit ANONYMOUS for trips that you can start guiding. 

* Vacancy 
As an ANONYMOUS tour guide, you will be responsible for expertly guiding our trips (bus and air travel) and you will ensure proper implementation of the technical and organizational aspects (accommodation, transport, contact with local agent). You are the face of our organization and ensure a perfect travel experience, both executive and content-wise. You introduce people to a destination and ensure that a fun and friendly group atmosphere is created. 

* Job Requirements 
- Lots of travel experience; 
- Experience in leading groups on multi-day trips; 
- Experience in the field of knowledge transfer (Eg. education) is a plus; 
- Cultural and historical knowledge; 
- Good communication and interpersonal skills; 
- Attention to group processes; 
- Able to create a good atmosphere in the group of single persons; 
- Knowledge of the English and German language and preferably French and/or Spanish; 
- Flexible, creative, good improvisation skills, stress resistant; 
- Natural authority and the ability to take charge. 
* Company Description 
- ANONYMOUS is an all-round and versatile tour operator, annually organizing the holidays of more than 300,000 passengers. Our product range is very diverse, ranging from well prepared excursion and tours, car trips, cruises, beach holidays, trips for singles to sporting holidays to more than 70
countries in the world. Every day, we develop new voyages, which makes ANONYMOUS one of the most dynamic organizations in the country. 

* Contact Information 
For more information please contact the Personnel Department: ANONYMOUS
