#+TITLE: visser 
- Job ID: 106882 
- Locatie: USA, overal in de U.S. 
- Salaris: $ 39.120 $ 39.975 per jaar 
- Status: Full Time 
- JobLevel: Mid Career 
- Bedrijf: National Oceanic & Atmospheric Administration 
- Contact: anonymized
- anonymized
- Norfolk, VA 23510 
- USA 
- Telefoon: anonymized
- Fax: anonymized
- URL: anonymized

* Job Beschrijving
Het hebben van een carrière als Verloond Marine werknemer in NOAA betekent een integraal onderdeel zijn van het begrijpen van de toestand van de oceaan en sfeer. NOAA Verloond Marine personeel voegt de knowhow van een zeeman toe aan het wetenschappelijk onderzoek van NOAA's door rechtstreeks deelnemen aan de bediening en het gebruik van wetenschappelijke uitrusting in het woelige milieu van de oceaan. NOAA's vloot onderzoeksschepen opereert wereldwijd in directe ondersteuning van NOAA's diverse milieu-informatieprogramma's, zorg voor het milieu diensten en toegepast wetenschappelijk onderzoek. 

De technische met vele vaardigheden medewerkers bieden NOAA de mogelijkheid op succes het uitvoeren van nautische kaarten, 
bathymetrische kaarten, visserijonderzoek, ecosysteem beoordelingen, zeemilieu basis beoordelingen, circulatie aan oceaankust, en oceanisch en atmosferisch onderzoek. 

Geniet van een boeiende carrière die als een federale werknemer, terwijl u ervaring en opleiding krijgt om uw zee- of persoonlijke referencies uit te bouwen. 

NOAA zeelieden aan boord hebben een uitstekend totale compensaties pakket dat ziekteverzekering omvat (optioneel), levensverzekering (optioneel), betaalde vakantie, ziekte verlof, en verlof om te passagieren (shore leave), periodieke gesubsidieerd vakantiereizen, pensioenplan, participatie in fondsen die voldoen aan het Thrift Savings Plan (vergelijkbaar met 401K) en overuren (niet gegarandeerd) die aanzienlijk kan aanvullen uw jaarsalaris. 

De visser geselecteerd voor deze functie zal: 
Kleine boten besturen; onderhoud en instandhouding van de schepen; lijnen hanteren en gooien bij het aanleggen en vertrekken van schepen (inclusief het opwinden en splitsen van draden en een aangetoonde kennis van basisknopen, -steken en splitsen); bediening dek apparatuur en benodigdheden (de veilige goede werking van kranen, davits, A-frames, achtersteven laadklep, lieren, en ankerlier). Vissersgereedschap hanteren, constructie of assemblage, en de reparatie, het repareren van netten (het repareren van netten omvat goring, yorking, trimmen en herstellen holes.)

Het uitvoeren van andere missie gerelateerde taken als opgedragen, inclusief taken in verband met de veiligheid van het schip en het personeel. 

* Minimale Geschiktheidsvereisten: 
- Amerikaans Staatsburger
- USCG MMC bekrachtigd met Matroos (Speciaal, Licht- of Volmatroos). [fn:: De kandidaten die zeer wenselijke visserij ervaring en / of vaardigheden tonen kunnen vrijgesteld worden van de eisen Matrooscertificaat. Wanneer hij is ingehuurd op een vrijstelling, moet de werknemer een akkoord tekenen dat hij / zij een kwalificerende Matroosvergunning zal behalen (Special, Lichtmatroos of Volmatroos) binnen een (1) jaar van benoeming of worden teruggebracht tot Gewoon zeeman / Gewoon visser. Applicanten ingehuurd onder vrijstelling het Matroos certificaat endorsement zijn nog steeds verplicht om minimaal een beginners Merchant Mariner Credential (MMC) te bezitten.]
- Moet ten minste zes (6) maanden gespecialiseerde Visserij ervaring hebben. [fn:: Gespecialiseerd ervaring is gedefinieerd als het besturen van een kleine boot, onderhoud en instandhouding van de schepen; lijnen hanteren, de wacht houden, gebruiken, inzetten en ophalen van een breed gala aan vistuig en bijbehorende wetenschappelijke apparatuur.]
- Voldoen aan de fysieke eisen, voorafgaand aan de afspraak. 
- Moet aan een drugs tests voldoen, voorafgaand aan zijn benoeming. 
- Moeten aan hun verplichtingen aangaande de dienstplicht voldaan hebben. 
- Voldoet aan Federale geschiktheid normen. 
