* JV 
- Job Title: SERVING ASSISTANT
- Job Number: NL_JV_1 
- Employer: Dxxxx, HXXXX 
- Employer Number: XXXX 
- Registration: 08/21/2014 Job 
- Employee: Registration LXXX. Work Company HaXXX 
- Change Date: 08/21/2014 
- Employee: mutation LXXX. Work Company HaXXX 
- Owner: HXXXX, Werkbedrijf AXXXX 
- Status: Active 
- Expiry date: 13/11/2014 
- Response Deadline: 13/11/2014 
- Presentation: None 
- Presentation date change: From 

** Job Characteristics
- EURES: No 
- Occupation: Assistant Hotel/Restaurant/Cafe operation 
- (Behavioral) Competencies: Deal with pressure and adversity. Focus on the needs and expectations of the "customer", collaboration and consultation, follow instructions and procedures
- Job description: As an serving assistant you are part of our Hotel/Restaurant/Cafe department where hospitality and service are of paramount importance. Our Hotel/Restaurant/Cafe department consists of several restaurants, bars and lounges, which makes for a lot of variety. 
- Extra Information: Besides serving our guests, you are responsible for achieving sales and service-oriented goals that are set in the department. You're a real host / hostess and thus a point of contact for our guests. Along with our catering team and our other departments you contribute to carefree enjoyment for our guests a day. The working hours at our Hotel/Restaurant/Cafe Department are between 08.30 to 00.30. You are working in rotating shifts both day, in the evening and in weekends and public holidays. 
- Number of jobs: 1 
- Number of applicants: 10 
- Requirements: You love and hospitality of people, are a real host / hostess and puts the guest central, enthusiastic, good social and communication skills. You can cope with pressure and changes, targeted and cost-conscious. Requires training or experience in hospitality and HACCP and hygiene regulations 
** requirements
- Professional experience: 
- Minimum experience: - Month (s) 
- Education: MBO-4 
- Driving license: N.A. 
- Work Location Type: HIERDEN 
- Travel Distance: 35 km 
- Contract: Temporary / possible fixed 
- Contract duration: 6 month (s) 
- First day: 21.08.2014 
- Salary indication: - 
- Working hours per week: 24-32 hours 
- Explanation of terms: We offer you a challenging and varied job in a very professional and progressive company. The salary is according to the Horeca CAO. 
- Normal working hours: Yes 
- Shift work: No 
- Emergency service: No 
- Application methods: Via contact Werkbedrijf, E-mail with your motivation and CV 
- Application address: XXXXX 
- Job Address: HXXXXX 
- Contact application procedure: LXXX. Work Company HaXXX 
- Contact information for Jobs: LXXX. Work Company HaXXX 
** Log 
- 21-08-2014: Mutation 
- 21-08-2014: Change, Create Jobs, Job Creation Lxxxx 
* Registration options 
** Vacancy Registration
- Job Number: NL_JV_1 
- Registration: 
- Last change: 21-08-2014 
** Owner
XXXX@uwv.nl 
Dep. owner 

- Establishment Werkbedrijf AcXXXXX 
- Job Type: [Regular job, apprenticeship, Volunteering, Work Experience Placement] 

- Status: [Active Blocked Repealed] [Partially fulfilled via Werkbedrijf, filled via another channel, Withdrawn, Not suitable offerings caseload] 
- Expiry date * Set 6 weeks further 
- Response time * Set 6 weeks further 
- Presentation * Open Anonymous No search without presenting 
But from ... ---------- Open Anonymous None 
- Referencing Referencing only by Owner 
- Yards abroad only mention on EURES Portal 
   - Via EURES - European 
   - Via EURES - Cross Border 
- Job Characteristics [Immigrants, Chronically ill / disabled people, Trialplacement, VOG, Women] 

- Target [> 55 Social Affairs, WW, Youth Job WWB, WAJONG WSW Arbeidsgehandicapten] 

- Category: covenants, Social return, Covenant UWV, Social return, Covenant WSP, covenant * 

** Job Description
- Job Title * M / F 
- Profession * catering service assistant 
- Industry * - Choose an industry - Agricultural Sector Security & Surveillance Construction Contact Centres Retail Wholesale Restaurants ICT Industry & Technology Interior Care / industrial cleaning / cleaning Education / General Other pedagogical work / Uniform occupations Clerical / administrative Transportation and Logistics Business Services Care & 

* Welfare 
Competencies * Name Change Proc. 
- Deal with pressure and adversity
- Focus on the needs and expectations of the "customer"
- Collaborate and discuss 
- Follow Instructions and procedures 

* Job description 
(info center bank name) * As serving assistant, you are part of our Hotel/Restaurant/Cafe department where hospitality and service are of paramount importance. Our Hotel/Restaurant/Cafe department consists of several restaurants, bars and lounges, which makes for a lot of variety. 


** Additional Job description 
Besides serving our guests you are responsible for achieving sales and service-oriented goals that are set in the department. You're a real host / hostess and thus a contact for our guests. Along with our Hotel/Restaurant/Cafe team and our other departments, you contribute to carefree enjoyment for our guests a day. 

The working hours at our Hotel/Restaurant/Cafe Department are between 08.30 to 00.30. You are working in rotating shifts both during the day, in the evening and in weekends and public holidays.

** Summary contract 
- Temporary / possible solid, 24-32 hours 
- Number of jobs * Number passed: 0 
- Number of applicants Number of sites: 0 

** Job requirements
- Job requirements: You love and hospitality and people, are a real host / hostess and place the guest central, enthusiastic, have good social and communication skills. You can cope with pressure and changes, targeted and cost-conscious. B.v.k. training or experience in hospitality and HACCP and hygiene regulations 

- Professional experience: Copy job 
- Experience: Min. months 

- Training * Global education / sector specific training name 
- Education * - Choose a level of education - Primary VMBO HAVO / VWO first MBO MBO MBO-2-3-4 MBO MBO generally HBO / WO bachelor / master 
- Sector - All - Automation and ICT Health, wellness and personal care Commerce and Administration Catering and housekeeping Agriculture, Nature and Environmental Education, Culture and Science Public governance, security and justice Storage and transport personnel, organization and strategy, Language, Media and Communication Engineering and manufacturing Tourism and leisure 

- Sub - All - 
Name Diploma V.o. Proc. 

- Proficiency Language Spoken Written Proc. 

** Driving license * N.A. 
required desired
vehicle Trailer 
- AM - Moped 
- A - Motor 
- B - Car BE 
- C1 - Light truck C1E 
- C - CE Truck 
- D1 - Light bus D1E 
- D - Bus passenger DE 
- T - Tractor 

** Work Location 
- Fixed jobsite Changing work location (Alt + X) Abroad (Alt + Y) 
- Postcode * XXXX 
- Maximum distance * km 
- Region * Regions in which one will work [Groningen, Friesland, Drenthe, Overijssel, North Brabant, Gelderland, Utrecht, Noord-Holland, Zuid-Holland, Zeeland, Limburg, Flevoland] 

- Country * - Choose a country - Belgium Germany Netherlands Afghanistan Albania Algeria American Samoa American Virgin Islands Andorra Angola Anguilla Antarctica Antigua and Barbuda Argentina Armenia Aruba Australia Austria Azerbaijan Bahamas Bahrain Bangladesh Barbados Belgium Belize Benin Bermuda British Virgin Islands Bhutan Bolivia Bosnia and Herzegovina Botswana Bouvet Island Brazil British Indian Ocean Territory Brunei Darussalam Bulgaria Burkina Faso Burundi Cambodia Canada Central African Republic Chad Chile China Christmas Island Cocos Islands Colombia Comoros Congo Congo Cook Islands Costa Rica Cuba Cyprus Denmark Djibouti Dominica Dominican Republic Ecuador Egypt El Salvador Equatorial Guinea Eritrea Estonia Ethiopia Falkland Islands Faroe Islands Fiji Philippines Finland France French Guiana French Polynesia French Southern Territories Gabon Gambia Georgia Ghana Gibraltar Greece Greenland Grenada Guadeloupe Guam Guatemala Guinea Guinea-Bissau Guyana Haiti Heard Island and McDonald Islands Honduras Hong Kong Hungary Iceland India Indonesia Iran Iraq Ireland Isle of Man Israel Italy ivory Coast Jamaica Japan Jordan Cape Verde Islands Cayman Islands Cameroon Kazakhstan Kenya Kiribati Croatia North Korea Kuwait Kyrgyzstan Laos Latvia Lebanon Lesotho Liberia Libya Liechtenstein Lithuania Luxembourg Macao Macedonia Madagascar Malawi Malaysia Maldives Mali Malta Marshall Islands Martinique Mauritania Mauritius Mayotte Mexico Micronesia Moldova Monaco Mongolia Montserrat Morocco Mozambique Myanmar Namibia Nauru Nepal Netherlands Netherlands Antilles New Caledonia New Zealand Nicaragua Niger Republic Nigeria Niue Norfolk Island Northern Mariana Islands Norway Oman Uganda Ukraine Uzbekistan Austria Pakistan Palau Palestine Panama Papua New Guinea Paraguay Peru Pitcairn Poland Portugal Puerto Rico Qatar Reunion Romania Russian Federation Rwanda Saint Helena Saint Kitts and Nevis Saint Lucia Santa Pierre and Miquelon St. Vincent and Grenada Samoa San Marino Sao Tome and Principe Saudi Arabia Senegal Serbia and Montenegro Seychelles Sierra Leone Singapore Slovak Republic Slovenia Solomon Islands Somalia Sandwich Islands Spain Sri Lanka Sudan Suriname Svalbard and Jan Mayen Swaziland Syria Taiwan Tajikistan Tanzania Thailand Timor-Leste Togo Tokelau Tonga Trinidad and Tobago Chad Czech Republic Tunisia Turkey Turkmenistan Turks and Caicos Islands Tuvalu United Arab Emirates United Kingdom United States United States Minor Outlying Islands Uruguay Vanuatu Vatican City Venezuela Vietnam Wallis and Futuna Belarus Western Sahara Yemen Zambia Zimbabwe South Africa South Korea Spain Sweden Switzerland 

street 
Postcode 
