* JV
- Vacaturetitel: MEDEWERKER BEDIENING 
- Vacaturenummer: NL_JV_1
- Werkgever: DXXXX, HXXXX
- Werkgevernummer: XXXX
- Registratiedatum: vacature 8/21/2014
- Medewerker: registratie LXXX. , WERKbedrijf HaXXX
- Mutatiedatum: 8/21/2014
- Medewerker: mutatie LXXX. , WERKbedrijf HaXXX
- Eigenaar: HXXXX , WERKbedrijf AXXXX
- Status: Actief
- Vervaldatum: 11/13/2014
- Reactietermijn: 11/13/2014
- Presentatie: Geen
- Presentatie datum wijziging: Vanaf

** Vacaturekenmerken	
- EURES: Nee
- Beroep: Medewerker bediening horeca
- (gedrags)Competenties: Met druk en tegenslag omgaan, Op de behoeften en verwachtingen van de "klant" richten, Samenwerken en overleggen, Instructies en procedures opvolgen
- Functieomschrijving: Als medewerker bediening maak je onderdeel uit van onze Horeca afdeling waar gastvrijheid en service hoog in het vaandel staan. Onze afdeling Horeca bestaat uit diverse restaurants, bars en lounges, wat zorgt voor veel afwisseling.
- Extra: nformatie		Naast het bedienen van onze gasten ben je medeverantwoordelijk voor behalen van verkoop en servicegerichte doelen die op de afdeling gesteld worden. Je bent een echte gastheer/gastvrouw en daarmee ook aanspreekpunt voor onze gasten. Samen met ons Horeca-team en onze andere afdelingen draag je bij aan een dag onbezorgd genieten voor onze gasten. De werktijden op onze Horeca afdeling liggen tussen 08.30 uur tot 00.30 uur. Je bent werkzaam in wisselende diensten die zowel overdag, s’ avonds als in weekenden en op feestdagen zijn.
- Aantal arbeidsplaatsen: 1
- Aantal sollicitanten: 10
- Functieeisen: Je houdt van horeca en van mensen, bent een echte gastheer/gastvrouw en stelt de gast centraal, enthousiast, sociaal en communicatief vaardig. Je kan goed omgaan met werkdruk en veranderingen, doelgericht en kostenbewust. B.v.k. opleiding of ervaring in horeca en HACCP en hygiënereglementen
** requirements
- Beroep ervaring:		
- Minimale ervaring:		- Maand(en)
- Opleiding:		MBO-4
- Rijbewijs:		N.v.t.
- Werklocatie type:		HIERDEN
- Reisafstand:		35 km
- Contract:		Tijdelijk/ mogelijk vast
- Contractduur:		6 maand(en)
- Eerste werkdag:		8/21/2014
- Salarisindicatie:		--
- Arbeidstijd per week:		24 - 32 uur
- Toelichting arbeidsvoorwaarden:		Wij bieden jou een uitdagende en zeer afwisselende baan binnen een professioneel en vooruitstrevend bedrijf. Het salaris is conform de Horeca CAO.
- Normale werktijden:		Ja
- Ploegendienst: Nee
- Storingsdienst: Nee
- Sollicitatiewijzen: Via contactpersoon WERKbedrijf, E-mail met motivatie en CV
- Sollicitatie emailadres:		XXXXX
- Sollicitatieadres:		HXXXXX
- Contactpersoon sollicitatieprocedure:		LXXX. , WERKbedrijf HaXXX
- Contactpersoon informatie over vacature:		LXXX. , WERKbedrijf HaXXX
** Logboek		
- 21-08-2014:	Mutatie	
- 21-08-2014:	Mutatie, Aanmaken vacature, Creatie vacature LXXXX
* Registration options
** Vacatureregistratie
- Vacaturenummer:  NL_JV_1
- Registratie: 
- Laatste mutatie:   21-08-2014 
** Eigenaar    
XXXX@uwv.nl
Plv. eigenaar
 
- Vestiging WERKbedrijf AcXXXXX
- Type vacature:    [ Reguliere vacature, Leerbaan, Vrijwilligerswerk, Werkervaringsplaats ]
 
- Status : [Actief Geblokkeerd Vervallen]   [Gedeeltelijk vervuld via WERKbedrijf, Vervuld via ander kanaal, Ingetrokken, Geen geschikt aanbod uit caseload ]   
- Vervaldatum *  Zet 6 weken verder  
- Reactietermijn *  Zet 6 weken verder  
- Presentatie *  Open Anoniem Geen Zoekopdracht zonder presentatie  
    ... maar   vanaf     ---------- Open Anoniem Geen  
- Verwijzen     Verwijzen alleen door eigenaar  
- Werven in het buitenland    Alleen vermelding op EURESportaal  
     - Via Eures - Europees  
     - Via Eures - Crossborder  
- Vacaturekenmerken [ Allochtonen,   Chronisch zieken/gehandicapten,  Proefplaatsing,   VOG,  Vrouwen ]
 
- Doelgroepen     [ > 55 SZW,   WW,  Jongerenbaan   WWB, Wajong   WSW, Arbeidsgehandicapten ]
 
- Categorie: convenanten, Social return, Convenant UWV, Social return, Convenant WSP, convenant *   

** Vacaturebeschrijving
- Vacaturetitel *    M/V  
- Beroep * Medewerker bediening horeca   
- Branche * - Kies een branche - Agrarische Sector Beveiliging en Bewaking Bouw Contactcenters Detailhandel Groothandel Horeca ICT Industrie & Techniek Interieurverzorging / industriële reiniging / schoonmaak Onderwijs / pedagogisch werk Overheid Overige / Uniforme beroepen Secretarieel / administratief Transport en logistiek Zakelijke dienstverlening Zorg & 

* Welzijn  
- Competenties *  Naam Wijzig Verw. 
- Met druk en tegenslag omgaan      
- Op de behoeften en verwachtingen van de "klant" richten      
- Samenwerken en overleggen      
- Instructies en procedures opvolgen      
 
* Functie-omschrijving 
(infocenter-banksheet)  * Als medewerker bediening maak je onderdeel uit van onze Horeca afdeling waar gastvrijheid en service hoog in het vaandel staan. Onze afdeling Horeca bestaat uit diverse restaurants, bars en lounges, wat zorgt voor veel afwisseling. 
 

** Extra Functie-omschrijving
Naast het bedienen van onze gasten ben je medeverantwoordelijk voor behalen van verkoop en servicegerichte doelen die op de afdeling gesteld worden. Je bent een echte gastheer/gastvrouw en daarmee ook aanspreekpunt voor onze gasten. Samen met ons Horeca-team en onze andere afdelingen draag je bij aan een dag onbezorgd genieten voor onze gasten.

De werktijden op onze Horeca afdeling liggen tussen 08.30 uur tot 00.30 uur. Je bent werkzaam in wisselende diensten die zowel overdag, s’ avonds als in weekenden en op feestdagen zijn.
 
 
** Samenvatting contract
- Tijdelijk/ mogelijk vast , 24 - 32 uur  
- Aantal arbeidsplaatsen *     Aantal aangenomen: 0  
- Aantal sollicitanten       Aantal verwijzingen: 0  

** Functie-eisen
- Functie-eisen:    Je houdt van horeca en van mensen, bent een echte gastheer/gastvrouw en stelt de gast centraal, enthousiast, sociaal en communicatief vaardig. Je kan goed omgaan met werkdruk en veranderingen, doelgericht en kostenbewust. B.v.k. opleiding of ervaring in horeca en HACCP en hygiënereglementen 
 
- Beroep ervaring:   Kopieer beroep  
- Ervaring:   Min.  maanden 
 
- Opleidingen *  Globaal opleidingsniveau/sector    Specifieke opleidingsnaam    
- Opleidingsniveau * - Kies een opleidingsniveau - Basisonderwijs VMBO Havo/VWO MBO-1 MBO-2 MBO-3 MBO-4 MBO-algemeen HBO/bachelor WO/master  
- Sector  - Alle - Automatisering en ICT Gezondheidszorg, welzijn en persoonlijke verzorging Handel en administratie Horeca en huishouding Landbouw, natuur en milieu Onderwijs, cultuur en wetenschap Openbaar bestuur, veiligheid en rechtspraak Opslag en transport Personeel, organisatie en strategie Taal, media en communicatie Techniek en productie Toerisme en recreatie  

- Subsector  - Alle -  
   Naam Diploma V.o. Verw. 
 
- Taalvaardigheid  Taal Mondeling Schriftelijk Verw. 
 
** Rijbewijs  *  N.v.t.    
Eis    Wens   
Voertuig   Aanhanger   
  AM - Brommer     
  A - Motor     
  B - Auto   BE 
  C1 - Licht vrachtwagen   C1E 
  C - Vrachtwagen   CE 
  D1 - Lichte bus   D1E 
  D - Bus personenvervoer   DE 
  T - Trekker     
 

** Werklocatie
- Vaste werklocatie  Wisselende werklocatie (Alt+X)  In het buitenland (Alt+Y)  
- Postcode  *   XXXX 
- Maximale reisafstand *  km  
- Regio * Regio's waarin men zal gaan werken [Groningen, Friesland, Drenthe, Overijssel, Noord-Brabant, Gelderland, Utrecht, Noord-Holland, Zuid-Holland, Zeeland, Limburg, Flevoland]  
  
- Land * - Kies een land - België Duitsland Nederland Afghanistan Albanië Algerije Amerikaans Samoa Amerikaanse Maagdeneilanden Andorra Angola Anguilla Antarctica Antigua en Barbuda Argentinië Armenië Aruba Australië Azerbeidzjan Bahamas Bahrein Bangladesh Barbados België Belize Benin Bermuda Britse Maagdeneilanden Bhutan Bolivia Bosnië-Herzegovina Botswana Bouvet Island Brazilië British Indian Ocean Territory Brunei Darussalam Bulgarije Burkina Faso Burundi Cambodja Canada Centraal-Afrikaanse Republiek Chili China Christmas Island Cocos Eilanden Colombia Comoros Republiek Congo Democratische Republiek Congo Cook Eilanden Costa Rica Cuba Cyprus Denemarken Djibouti Dominica Dominicaanse Republiek Duitsland Ecuador Egypte El Salvador Equatoriaal Guinea Eritrea Estland Ethiopië Falkland Eilanden Faroer Eilanden Fiji Filipijnen Finland Frankrijk Frans Guyana Frans Polynesië Franse Zuidelijke Territories Gabon Gambia Georgië Ghana Gibraltar Griekenland Groenland Grenada Guadeloupe Guam Guatemala Guinea Guinea-Bissau Guyana Haiti Heard Eiland en McDonald Eilanden Honduras Hongkong Hongarije IJsland India Indonesië Iran Irak Ierland Isle of Man Israël Italië Ivoorkust Jamaica Japan Jordanië Kaap Verdische eilanden Kaaiman eilanden Kameroen Kazachstan Kenia Kiribati Kroatië Noord-Korea Koeweit Kirgizië Laos Letland Libanon Lesotho Liberia Libië Liechtenstein Litouwen Groothertogdom Luxemburg Macao Macedonië Madagaskar Malawi Maleisië Malediven Mali Malta Marshall Eilanden Martinique Mauritanië Mauritius Mayotte Mexico Micronesië Republiek Moldavië Monaco Mongolië Montserrat Marokko Mozambique Myanmar Namibië Nauru Nepal Nederland Nederlandse Antillen Nieuw-Caledonië Nieuw-Zeeland Nicaragua Republiek Niger Nigeria Niue Norfolk Eiland Noordelijke Mariana Eilanden Noorwegen Oman Oeganda Oekraïne Oezbekistan Oostenrijk Pakistan Palau Palestina Panama Papua Nieuw Guinea Paraguay Peru Pitcairn Polen Portugal Puerto Rico Qatar Reunion Roemenië Russische Federatie Rwanda Sint Helena Sint Kitts en Nevis Santa Lucia Sint Pierre en Miquelon Sint Vincent en Grenada Samoa San Marino Sao Tome en Principe Saoedi-Arabië Senegal Servië en Montenegro Seychellen Sierra Leone Singapore Slowakije Slovenië Solomon Eilanden Somalië Sandwich Eilanden Spanje Sri Lanka Soedan Suriname Svalbard en Jan Mayen Swaziland Syrië Taiwan Tadzjikistan Tanzania Thailand Timor Leste Togo Tokelau Tonga Trinidad en Tobago Tsjaad Tsjechië Tunesië Turkije Turkmenistan Turks en Caicos Eilanden Tuvalu Verenigde Arabische Emiraten Verenigd Koninkrijk Verenigde Staten United States Minor Outlying Eilanden Uruguay Vanuatu Vaticaanstad Venezuela Vietnam Wallis en Futuna Wit-Rusland Westelijke Sahara Jemen Zambia Zimbabwe Zuid-Afrika Zuid-Korea Zweden Zwitserland  

Straat       
Postcode    
Plaats    

