#+TITLE: Dierenverpleger
- Omschrijving: Dierenverpleger - Huisdierenzorg
- £ 20,000 £ 27,000 + uitstekende secundaire arbeidsvoorwaarden 
- Waltham, in de buurt van Melton Mowbray, Leics. 

* Over ANONYMOUS 
De ANONYMOUS Centre for Pet Nutrition is een toonaangevende wetenschappelijke autoriteit in dierenvoeding en welzijn en is verlegt de grenzen van wetenschappelijke onderzoek naar voeding en gezondheid van huisdieren voor meer dan 50 jaar. ANONYMOUS is het fundamentele wetenschapscentrum voor ANONYMOUS Petcare en richt zich op de voeding en het welzijn van honden, katten, paarden, vogels en vissen, en de voordelen ervan voor de mens. Bij ANONYMOUS verplichten we ons tot het creëren van een betere wereld voor dieren, we produceren toonaangevende merken zoals ANONYMOUS en ANONYMOUS. De kennis die ANONYMOUS verwerft is van vitaal belang in het tot leven brengen van deze visie. 

De kern van ons succes is onze aanpak die streeft naar het verzorgen van onze huisdieren in een verrijkte omgeving met een hoge standaard van zorg die zowel hun gezondheid en geluk verzekert. We noemen dit onze Caring Science aanpak. 

Uw belangrijkste verantwoordelijkheid als Dierenverpleger zal zijn voor de coördinatie en ondersteuning van de uitvoering van de ANONYMOUS gezondheidszorg programma om ons research plan te ondersteunen. Verantwoording afleggend aan onze Pet Behaviour and Care Manager, zult u de dierenarts ondersteunen tijdens de rondes en de operatie, in nauw contact met ons research team om ervoor te zorgen alle huisdieren geschikt zijn om deel te nemen aan de proeven. 

* Belangrijke verantwoordelijkheden zijn onder andere: 
- verlenen van verpleegkundige ondersteuning tijdens veterinaire rondes en chirurgie
- onderhoud van de veterinaire suites en de hond quarantaine-eenheid 
- lid van een cross-site team dat gespecializeerde procedures uitvoert op de dieren
- nauw samen met ervaren collega's om de coördinatie en levering van al onze gezondheidsprogramma's aan te drijven. 

Met een Certificaat in Dierengeneeskunde, evenals de registratie, en het liefst met een Universitaire Bachelor of Hogeschool (orig. Foundation Degree) gediplomeerd dierenarts verpleging, je moet een bewezen track record bezitten binnen een kleine veterinaire praktijk. Je hebt interesse in het gedrag van dieren, lowstress handling, in het ideale geval bewezen door voltooiing van een bijscholing in deze gebieden. Uw vermogen om effectief te werken binnen een team vult uw functioneel-technische vaardigheden aan. U vindt hier ook meeU Brengt ook: 
- bewezen ervaring in het werken binnen, en uitbouwen van, een effectief team
- streven naar perfectie, door middel van prestatie-evaluatie en continue verbetering 
- de mogelijkheid om samenwerkingsverbanden te creëren
- echte klantgerichtheid. 

We verwachten dat je binnen een jaar een training volgt als persoonlijk licentie-houder, zoals beschreven in de Wetenschappelijke Procedure Act voor Dieren. 

ANONYMOUS is maar 40 minuten pendelen van Leicester, Nottingham of Newark. 

Dus als we zonet u en uw ambities hebben beschreven, klikt u dan op de onderstaande link. In ruil daarvoor zullen we u ongeëvenaarde ondersteuning voor uw persoonlijke en professionele ontwikkeling en de kans om te werken met een team van wereldklasse van veterinaire professionals geven.
