#+TITLE:Veterinary Nurse
- Description
- Veterinary Nurse – Petcare
- £20,000 ­ £27,000 + excellent benefits                                  
- ANONYMOUS, near Melton Mowbray, Leics.
 
* About ANONYMOUS
The ANONYMOUS Centre for Pet Nutrition is a leading scientific authority in pet nutrition and wellbeing and has been advancing the frontiers of scientific research into nutrition and health of pets for over 50 years. ANONYMOUS is the fundamental science centre for Mars Petcare and focuses on the nutrition and wellbeing of dogs, cats, horses, birds and fish, and their benefits to humans. At ANONYMOUS we are committed to creating a better world for pets, producing market leading brands such as ANONYMOUS and ANONYMOUS. The knowledge generated by ANONYMOUS is vital in bringing this vision to life.
 
At the heart of our success is an approach that strives to look after our pets in an enriched environment with a high standard of care that ensures both their health and happiness. We call this our Caring Science approach.
 
Your key responsibility as Veterinary Nurse will be to co­ordinate and support delivery of the ANONYMOUS healthcare programme to support our research plan.  Reporting to our Pet Behaviour and Care Manager, you’ll support the Veterinary Surgeon during rounds and surgery, liaising closely with our research team to ensure all pets are fit to participate in trials.

* Major accountabilities include:
provision of nursing support during veterinary rounds and surgery maintenance  of the veterinary suites and the dog quarantine unit member of a cross­site team performing specialist animal procedures working closely with senior colleagues to drive the co­ordination and delivery of all our healthcare programmes.
 
With a RCVS Certificate in Veterinary Nursing, along with registration, and ideally with a BSc or FdSc degree in veterinary nursing, you must have a proven track record within a small animal veterinary practice. You have an interest in animal behaviour, low­stress handling, ideally proven by completion of CPD in these areas. Your ability to work effectively within a team complements your functional­technical skills. You’ll also bring: proven experience working within, and building, an effective team commitment to excellence, through performance evaluation and continuous improvement the ability to create collaborative relationships real customer focus.
 
We’ll expect you to complete training as a personal licence­holder as outlined in the Animal Scientific Procedure Act within one year.
 
ANONYMOUS is just a 40­minute commute from Leicester, Nottingham or Newark.
 
So if we’ve just described you and your aspirations, simply click on the link below. In return we will give you unrivalled support for your personal and professional development and the opportunity to work with a world­class team of veterinary professionals.
